In [ ]:
#Model Evaluation
myknn = KNeighborsClassifier(n).fit(X_train,y_train) #fits KNN model,n nearest neighbors

In [ ]:
predictions = myknn.predict(X_test) #model is applied to test data

In [ ]:
myknn.score(X_test, y_test) #test data is scored

In [ ]:
from sklearn import metrics

print metrics.classification_report([sk_iris['target_names'][label] for label in y_test], 
                                    [sk_iris['target_names'][label] for label in myknn.predict(X_test)])

In [ ]:
#Ordinary Least Squares
results = sm.OLS(y, x).fit() #fits the data
slope = results.params[0] #params gives betas
r2 = results.rsquared #r2 value(coefficient of determination) regression score function. 
#Best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). 
#A constant model that always predicts the expected value of y, disregarding the input features, 
#would get a R^2 score of 0.0.
print slope
print r2

In [ ]:
X = sm.add_constant(x, prepend=True) #adds constant to find y intercept

In [ ]:
results = sm.OLS(y, X).fit()
intercept, slope = results.params #fitting an intercept and getting slope, shifts the line

r2 = results.rsquared #deviations of predicted from actual empirical values of data, A small RSS indicates a tight fit of the model to the data.

print intercept,slope
print r2

In [ ]:
#Function of Multiple variables
x = data_n[['sqft', 'bdrms','age']].values
y = data_n['price'].values

X = sm.add_constant(x, prepend=True)
results = sm.OLS(y, X).fit()

In [ ]:
#stats Formula API
import statsmodels.formula.api as smf
results = smf.ols('price ~ sqft + bdrms', data=data).fit()
results.summary()

In [ ]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=0) #20% test size 80% data size

In [ ]:
from sklearn.linear_model import LogisticRegression

features = spam_data.drop('is_spam',axis=1)
target = spam_data.is_spam

model_lr = LogisticRegression(C=1) #regularzation of 1

In [ ]:
cross_val_score(model_lr,features,target,cv=10).mean() #cv 5-10, cv is number of folds of data to test

In [ ]:
#Non Linear Function
#y=1/2x+1/2sinx−1/50(x−5)2 + 5
# start with some fake data
nsample = 50
sig = 0.5
# generate linear space
x = np.linspace(0, 20, nsample) #generate 50 numbers,range 0-20
# invent function
X = np.c_[x, np.sin(x), (x - 5)**2, np.ones(nsample)] #Return a new array of given shape and type, filled with ones.
# invent coefficients
beta = [1.5, 2.5, -0.2, 15.]
# generate |
y_true = np.dot(X, beta) #np.dot = multiple arrays
# add noise
y = y_true + sig * np.random.normal(size=nsample)

In [ ]:
X = np.c_[x, np.sin(x), (x - 5)**2, np.ones(nsample)]
X.shape
x.shape
y_true.shape

In [ ]:
res = sm.OLS(y, X).fit()
res.summary()

In [ ]:
print res.params #betas or coef

In [ ]:
print res.bse #error

In [ ]:
#dummy variables for categorical dataj
>>> from sklearn.preprocessing import OneHotEncoder
>>> enc = OneHotEncoder()
>>> enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])  
OneHotEncoder(categorical_features='all', dtype=<... 'float'>,
       handle_unknown='error', n_values='auto', sparse=True)
>>> enc.n_values_
array([2, 3, 4])
>>> enc.feature_indices_
array([0, 2, 5, 9])
>>> enc.transform([[0, 1, 1]]).toarray()
array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.]])

In [ ]:
#sparse
[010] = [0,1]
[100] = [1,0]
[001] = [2,2]

In [2]:
#
import json
py_object = [ { 'a':'A', 'b':(2, 4), 'c':3.0 } ] 
json_string = json.dumps(py_object) 
print 'JSON:', json_string

JSON: [{"a": "A", "c": 3.0, "b": [2, 4]}]


In [4]:
decoded_py_object = json.loads(json_string)
print decoded_py_object

[{u'a': u'A', u'c': 3.0, u'b': [2, 4]}]


In [ ]:
#find null values
df.isnull().values.any()

In [3]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 4
np.vander(x, N)


array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [ ]:
#Naive Bayes, logistic regr, knn, decission trees

In [9]:
import numpy as np
x = np.array([1, 2, 3, 5])
y = np.array([2, 4, 6, 10])
xx,yy= np.meshgrid(x),np.meshgrid(y)
xx,yy

([array([1, 2, 3, 5])], [array([ 2,  4,  6, 10])])

In [22]:
nx, ny = (3, 2)
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 2)
print x
print y
xv, yv = np.meshgrid(x, y)
xv,yv


[ 0.   0.5  1. ]
[ 0.  1.]


(array([[ 0. ,  0.5,  1. ],
        [ 0. ,  0.5,  1. ]]), array([[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]]))

In [ ]:
from sklearn.cross_validation import cross_val_score

features = titanic[feature_columns]
target = titanic['Survived']

forest_size = range(2,100,2)
y = []
for i in forest_size:
    rfc = RandomForestClassifier(max_depth=5, n_estimators=i, max_features=4)
    accuracy = cross_val_score(rfc, features, target, cv=5).mean()
    
    y.append(accuracy)
p1 = figure(title='Random Forest Classifier performance',tools='')
p1.line(x=forest_size,y=y, color='green')


show(p1)